// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDNUGTU6EdTt9cX9L_AQTt9k4IY7_V3irU',
    appId: '1:687494407269:web:e738f5399d640dfe65128c',
    messagingSenderId: '687494407269',
    projectId: 'chess-app-23456',
    authDomain: 'chess-app-23456.firebaseapp.com',
    storageBucket: 'chess-app-23456.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB_TPiUL2md4fcDFGuognJznBt-DsIyuzw',
    appId: '1:687494407269:android:b6b59648d42967ec65128c',
    messagingSenderId: '687494407269',
    projectId: 'chess-app-23456',
    storageBucket: 'chess-app-23456.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCvkcdgh-Sx2vjV01RW-p_B1OlHgeGBbAs',
    appId: '1:687494407269:ios:d912650fbf0c136165128c',
    messagingSenderId: '687494407269',
    projectId: 'chess-app-23456',
    storageBucket: 'chess-app-23456.appspot.com',
    iosClientId: '687494407269-8rqojvj1afu3h8l5nm56hbng8buvvr24.apps.googleusercontent.com',
    iosBundleId: 'com.dawidwrobel.chessApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCvkcdgh-Sx2vjV01RW-p_B1OlHgeGBbAs',
    appId: '1:687494407269:ios:d912650fbf0c136165128c',
    messagingSenderId: '687494407269',
    projectId: 'chess-app-23456',
    storageBucket: 'chess-app-23456.appspot.com',
    iosClientId: '687494407269-8rqojvj1afu3h8l5nm56hbng8buvvr24.apps.googleusercontent.com',
    iosBundleId: 'com.dawidwrobel.chessApp',
  );
}
